const requiredDocs=['PAN / Tax ID proof','Business registration proof','Bank account proof','Address proof'];
const optionalDocs=['GST registration proof','Website / storefront evidence'];
const entities=['','Sole Proprietorship','Partnership','LLP','Private Limited Company','Public Limited Company','Trust / Society'];
const categories=['','Retail / ecommerce','Food / restaurant','IT / professional services','Healthcare','Education','Travel / hospitality','High-value precious metals','Gaming / betting','Crypto / virtual assets','Cross-border remittance','Other'];
const turnovers=['','Below ₹25 lakh','₹25 lakh - ₹1 crore','₹1 crore - ₹5 crore','Above ₹5 crore'];
const enhanced={'Gaming / betting':'Category requires enhanced human review under the prototype rules.','Crypto / virtual assets':'Virtual-asset activity requires enhanced human review under the prototype rules.','Cross-border remittance':'Cross-border financial activity requires enhanced human review under the prototype rules.','High-value precious metals':'Precious-metals activity requires enhanced human review under the prototype rules.'};
const cases=[
{business_name:'BluePeak Retail Pvt Ltd',entity_type:entities[4],pan:'AABCB1234C',gstin:'27AABCB1234C1Z9',bank_holder:'BluePeak Retail Pvt Ltd',bank_last4:'4821',category:categories[1],website:'https://bluepeak-demo.example',turnover:turnovers[2],years:4,docs:[...requiredDocs,...optionalDocs],notes:'Merchant sells consumer home accessories through a small ecommerce storefront.'},
{business_name:'Sunrise Foods',entity_type:entities[1],pan:'ABCDE1234F',gstin:'',bank_holder:'Sunrise Foods',bank_last4:'',category:categories[2],website:'',turnover:turnovers[1],years:2,docs:[requiredDocs[0],requiredDocs[3]],notes:'Application submitted before all supporting documents were collected.'},
{business_name:'Northstar Digital Services LLP',entity_type:entities[3],pan:'AABFN5678K',gstin:'27AABFN5678K1Z2',bank_holder:'N Star Consulting',bank_last4:'7712',category:categories[3],website:'https://northstar-demo.example',turnover:turnovers[3],years:5,docs:[...requiredDocs,optionalDocs[0]],notes:'Bank proof is available, but the account-holder name differs from the legal business name.'},
{business_name:'Orbit Metals Traders LLP',entity_type:entities[3],pan:'AABFO2468R',gstin:'27AABFO2468R1Z5',bank_holder:'Orbit Metals Traders LLP',bank_last4:'9044',category:categories[7],website:'https://orbit-demo.example',turnover:turnovers[4],years:7,docs:[...requiredDocs,...optionalDocs],notes:'Basic information is present, but the category requires enhanced human due diligence.'}];
const fieldDefs=[['business_name','Business / legal name',null,true],['entity_type','Entity type',entities,true],['pan','PAN (dummy)',null,true],['gstin','GSTIN (if applicable)'],['bank_holder','Bank account-holder name',null,true],['bank_last4','Account last 4 digits',null,true],['category','Business category',categories,true],['turnover','Reported annual turnover',turnovers,true],['website','Website / storefront'],['years','Years in operation'],['notes','Business description / reviewer context']];
const $=id=>document.getElementById(id);const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalizeName(v){return v.toLowerCase().replace(/\b(pvt|private|limited|ltd|llp|company|co|inc|enterprise|enterprises)\b/g,' ').replace(/[^a-z0-9 ]/g,' ').trim().replace(/\s+/g,' ')}
function nameSimilarity(a,b){a=normalizeName(a);b=normalizeName(b);if(!a||!b)return 0;function matches(a0,a1,b0,b1){let best=0,ai=a0,bj=b0,prev={};for(let i=a0;i<a1;i++){const row={};for(let j=b0;j<b1;j++)if(a[i]===b[j]){const size=(prev[j-1]||0)+1;row[j]=size;if(size>best){best=size;ai=i-size+1;bj=j-size+1}}prev=row}return best?best+matches(a0,ai,b0,bj)+matches(ai+best,a1,bj+best,b1):0}return 2*matches(0,a.length,0,b.length)/(a.length+b.length)}
function analyseCase(d){const missing=[],issues=[],flags=[],evidence=[];const core=fieldDefs.filter(f=>f[3]);for(const [id,label]of core)if(!String(d[id]??'').trim())missing.push(label);const pan=d.pan.trim().toUpperCase(),gst=d.gstin.trim().toUpperCase();if(pan){if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan))issues.push('PAN does not match the 10-character demo format.');else evidence.push('PAN passes format validation; identity is not verified.')}if(gst){if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$/.test(gst))issues.push('GSTIN format is inconsistent and needs verification.');else evidence.push('GSTIN passes format validation; registration is not verified.')}if(d.bank_last4&&!/^\d{4}$/.test(d.bank_last4))issues.push('Bank account last 4 digits must contain exactly four numbers.');if(!Number.isInteger(Number(d.years))||Number(d.years)<0||Number(d.years)>100||d.years==='')issues.push('Years in operation must be a whole number from 0 to 100.');if(d.website){try{const url=new URL(d.website);if(!['http:','https:'].includes(url.protocol))throw Error();}catch{issues.push('Website must be a valid HTTP or HTTPS URL.');}}const missingDocs=requiredDocs.filter(x=>!d.docs.includes(x));if(missingDocs.length)issues.push('Missing supporting documents: '+missingDocs.join(', ')+'.');else evidence.push('All four core document categories are marked available.');let similarity=null;if(d.business_name&&d.bank_holder){similarity=nameSimilarity(d.business_name,d.bank_holder);if(similarity<.62)flags.push(`Legal-name / bank-account-name mismatch (${Math.round(similarity*100)}% prototype similarity). Human verification required.`);else evidence.push('Legal and bank account-holder names appear reasonably consistent.')}if(enhanced[d.category])flags.push(enhanced[d.category]);if(Number(d.years)===0&&d.years!=='')flags.push('Newly established business: review operating evidence.');const completeness=Math.round((11-missing.length-missingDocs.length)/11*100);const action=missing.length||issues.length?'REQUEST INFORMATION':flags.length?'ESCALATE FOR ENHANCED HUMAN REVIEW':'READY FOR HUMAN REVIEW';const summary=`${d.business_name||'The merchant'} is applying as a ${d.entity_type||'business entity'} in ${d.category||'an unspecified category'}, with reported annual turnover of ${d.turnover||'not provided'}. Completeness is ${completeness}%. ${flags.length?`${flags.length} enhanced-attention item(s) need investigation.`:missing.length||issues.length?'Additional information or corrections are needed.':'No obvious completeness or discrepancy issue was found by the prototype rules.'}`;return {completeness,missing,issues,flags,evidence,action,summary,similarity}}
let result=null,decision='Not reviewed',audit=[];
function eventLog(message){audit.unshift({at:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}),message});$('audit').innerHTML=audit.map(e=>`<li><time>${escapeHTML(e.at)}</time>${escapeHTML(e.message)}</li>`).join('')}
const emptyAnalysis='<div class="empty-symbol">◎</div><h3>Ready when you are.</h3><p class="hint">Run an analysis to see completeness, document gaps, and items that need a closer look.</p><div class="empty-check">✓ &nbsp; Explainable completeness checks</div><div class="empty-check">✓ &nbsp; Name and document discrepancies</div><div class="empty-check">✓ &nbsp; Human review always required</div>';
function clearReview(){result=null;decision='Not reviewed';$('analysis').innerHTML=emptyAnalysis;$('review-panel').hidden=true;$('review-reason').value='';$('decision-status').textContent='';$('review-error').textContent='';$('form-error').textContent='';$('step-analysis').classList.remove('done');$('step-review').classList.remove('current')}
function invalidate(){if(result){eventLog('Application changed. Previous analysis and decision cleared; run analysis again.');clearReview()}updateDocs()}
function updateDocs(){$('doc-count').textContent=`${[...document.querySelectorAll('[name=doc]:checked')].filter(e=>requiredDocs.includes(e.value)).length} of 4 required`}
function loadCase(index){if(!Number.isInteger(index)||index<0||index>=cases.length)throw Error('Choose a demo scenario from 0 to 3.');clearReview();const d=cases[index];for(const [id]of fieldDefs)$(id).value=d[id];for(const el of document.querySelectorAll('[name=doc]'))el.checked=d.docs.includes(el.value);$('files').value='';$('filenames').textContent='';$('scenario').value=String(index);updateDocs();eventLog('Loaded fictional case: '+d.business_name)}
function readForm(){const d={};for(const [id]of fieldDefs)d[id]=$(id).value.trim();d.pan=d.pan.toUpperCase();d.gstin=d.gstin.toUpperCase();d.docs=[...document.querySelectorAll('[name=doc]:checked')].map(e=>e.value);return d}
function listSection(title,items,empty){return `<details class="findings" ${items.length?'open':''}><summary>${title} <span>(${items.length})</span></summary><ul>${(items.length?items:[empty]).map(s=>'<li>'+escapeHTML(s)+'</li>').join('')}</ul></details>`}
function processApplication(){const d=readForm();if(!d.business_name||!d.category){$('form-error').textContent='Enter a business / legal name and choose a business category.';(!d.business_name?$('business_name'):$('category')).focus();return false}clearReview();result=analyseCase(d);decision='Pending human review';const r=result;$('analysis').innerHTML=`<div class="stats"><div class="stat"><b>${r.completeness}<small style="font-size:19px">%</small></b><span>Application completeness</span></div><div class="stat"><b>${r.flags.length+r.issues.length}</b><span>Attention flags</span></div></div><div class="meter"><span style="width:${r.completeness}%"></span></div><div class="action ${r.action==='READY FOR HUMAN REVIEW'?'':'attention'}"><strong>${r.action}</strong><br>Human verification is required before any decision.</div><p class="summary">${escapeHTML(r.summary)}</p>${listSection('Missing information',r.missing,'All required text fields are present.')}${listSection('Issues & document gaps',r.issues,'No document or format issue detected.')}${listSection('Enhanced-review indicators',r.flags,'No enhanced-review flag detected.')}${listSection('Observed evidence',r.evidence,'No positive evidence recorded.')}<p class="analysis-footnote">Deterministic rule-based summary · Decision support only.<br>Completeness measures presence, not validity or eligibility.</p>`;$('review-panel').hidden=false;$('decision-status').textContent=decision;$('step-analysis').classList.add('done');$('step-review').classList.add('current');eventLog(`Analysis completed for ${d.business_name}: ${r.action}. Human review pending.`);return true}
function recordDecision(value){if(!result)return;const reason=$('review-reason').value.trim();if(!reason){$('review-error').textContent='Record a reviewer reason before making a decision.';$('review-reason').focus();return}$('review-error').textContent='';decision=value;$('decision-status').textContent=value;eventLog(readForm().business_name+' — '+value+'. Reason: '+reason)}
$('fields').innerHTML=fieldDefs.map(([id,label,options,required])=>`<div class="field ${id==='notes'?'wide':''}"><label for="${id}">${label}${required?' <span class="required">*</span>':''}</label>${options?`<select id="${id}" ${required?'aria-required="true"':''}>${options.map(v=>`<option value="${escapeHTML(v)}">${escapeHTML(v||'Select an option')}</option>`).join('')}</select>`:id==='notes'?`<textarea id="${id}" rows="2"></textarea>`:`<input id="${id}" ${id==='years'?'type="number" min="0" max="100" step="1"':id==='bank_last4'?'type="text" maxlength="4" inputmode="numeric"':'type="text"'} ${required?'aria-required="true"':''} autocomplete="off">`}</div>`).join('');
$('documents').innerHTML=[...requiredDocs,...optionalDocs].map((v,i)=>`<label class="doc"><input type="checkbox" name="doc" value="${escapeHTML(v)}"><span>${v}${i>=4?'<small>Optional</small>':''}</span></label>`).join('');
$('merchant-form').addEventListener('input',invalidate);$('merchant-form').addEventListener('change',invalidate);$('merchant-form').addEventListener('submit',e=>{e.preventDefault();processApplication()});$('load').addEventListener('click',()=>loadCase(Number($('scenario').value)));$('files').addEventListener('change',()=>{$('filenames').textContent=[...$('files').files].map(f=>f.name).join(', ')});document.querySelectorAll('[data-decision]').forEach(b=>b.addEventListener('click',()=>recordDecision(b.dataset.decision)));
const titles={workspace:['Onboarding workspace','A clearer path to merchant review.'],research:['Research sources','Grounded in public information.'],prompt:['Prompt engineering','Give assistance a clear boundary.'],controls:['About & controls','Human judgment, by design.']};document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.view);document.querySelectorAll('[data-view]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-current',n===b?'page':'false')});$('breadcrumb').textContent=titles[b.dataset.view][0];$('page-title').textContent=titles[b.dataset.view][1];document.querySelector('.subtitle').hidden=b.dataset.view!=='workspace'}));
for(const [id] of fieldDefs){const el=$(id);if(el.tagName==='INPUT'&&el.type!=='number'&&id!=='bank_last4')el.maxLength=id==='website'?500:160;if(el.tagName==='TEXTAREA')el.maxLength=2000;}
$('review-reason').maxLength=2000;
loadCase(0);
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_merchant_review_state',title:'Read merchant review state',description:'Read the currently displayed fictional application, rule-based analysis and human decision. Does not change state or make a decision.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');return {application:readForm(),analysis:result,decision}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}

$('rtocf').textContent="R - Role\nYou are an AI co-pilot supporting a bank merchant-onboarding analyst. You are NOT the final decision-maker.\n\nT - Task\nReview only the merchant information supplied in the case. Identify missing information, internal inconsistencies, document gaps and indicators that require enhanced human review. Produce a concise case summary and suggest the next workflow action.\n\nO - Output\nReturn: (1) completeness assessment, (2) missing information/documents, (3) discrepancies, (4) risk/attention indicators, (5) concise case summary, (6) suggested next action, and (7) explicit human-review requirement.\n\nC - Constraints\nDo not approve or reject a merchant. Do not invent facts, verification results or regulatory conclusions. If information is unavailable, state that it is unavailable. Separate observed facts from assumptions. Treat all model output as decision support. Use only dummy/anonymised data in this academic prototype. Escalate uncertain or high-risk cases to a human reviewer.\n\nF - Format\nUse structured headings or JSON-like fields: Completeness; Missing Items; Discrepancies; Risk Indicators; Case Summary; Suggested Next Action; Human Review Note.\n";
$('sources').innerHTML=[{"label":"YES BANK Merchant Application Form (Physical), V5.9 Apr 2025","url":"https://www.yesbank.in/content/published/api/v1.1/assets/CONT10B172F229B049B59BB1F99EE605AC07/native/ybl_pos_application_form.pdf"},{"label":"YES BANK Merchant Application Form (Insta/NEFT), V5.9 Apr 2025","url":"https://www.yesbank.in/content/published/api/v1.1/assets/CONT5E8719B5071F4D3CA651C86811F0B0B9/native/ybl_digital_insta_onboarding_form.pdf"},{"label":"YES BANK Integrated Annual Report 2023-24","url":"https://www.yesbank.in/content/published/api/v1.1/assets/CONTD667CD91C4274D5997BB6F99724C151C/native/ybl_integrated_annual_report.pdf"},{"label":"HDFC Bank SmartHub Vyapar","url":"https://www.hdfcbank.com/personal/save/accounts/current-accounts/vyapar-current-account"},{"label":"ICICI Bank eazypay online boarding","url":"https://eazypay.icicibank.com/MerchantOnBoard1.0/mob"},{"label":"Cashfree Secure ID","url":"https://www.cashfree.com/docs/secure-id/introduction"},{"label":"RBI merchant-onboarding / Payment Aggregator due-diligence guidance","url":"https://www.rbi.org.in/Scripts/PublicationReportDetails.aspx?ID=943&UrlPage="},{"label":"Razorpay POS partner docs","url":"https://razorpay.com/docs/partners/pos/"},{"label":"HyperVerge KYB","url":"https://hyperverge.co/solutions/kyb/"}].map(s=>`<a class="source" target="_blank" rel="noopener noreferrer" href="${escapeHTML(s.url)}"><span>${escapeHTML(s.label)}<small>Project-provided public reference</small></span><span>↗</span></a>`).join("");
